### ISSUE TITLE
Extra space is added at the start of the first item of a list when in read mode

### ISSUE THREAD

**Issue by XC3N** [clbn/dracula-gemini#1]
edit mode:
![image](https://github.com/user-attachments/assets/7d73f294-6c70-42e8-93d3-e2fccc85d852)

read mode:
![image](https://github.com/user-attachments/assets/d5ef9595-d537-47c0-a7c2-d81e8aa58a63)

this happens on every list of every page and does not happen when the theme is not active...

**Comment by clbn** [comment]
@XC3N Yeah, it's been bothering me for some time, but I never got around to fixing it. Thank you, I'll look into it.

**Comment by XC3N** [comment]
Thanks! Been growing dependant on that theme haha

**Comment by clbn** [comment]
@XC3N This is finally fixed, I just released [version 1.1.0](https://github.com/clbn/dracula-gemini/releases/tag/1.1.0).
